# Generated by Django 3.0.2 on 2020-02-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
